"""Detection signals for Provenance Guard.

Two INDEPENDENT signals, each returning P(AI-generated) in [0.0, 1.0]:

  Signal 1 - llm_signal()          Groq LLM-as-judge. Semantic/holistic read of
                                   whether the text sounds human or AI. This is
                                   the same LLM-as-judge pattern as RepairSafe's
                                   classify_safety_tier(), re-aimed at attribution.
                                   -> Milestone 3

  Signal 2 - stylometric_signal()  Pure-Python structural statistics (sentence
                                   length variance, vocabulary diversity,
                                   punctuation density). No API call. AI prose
                                   tends to be more uniform; human prose varies.
                                   -> Milestone 4

The DESIGN DECISIONS (the judge prompt + its output format, which metrics to
use and how to fold them into one score) belong in planning.md first. The
`TODO`s below mark exactly where those decisions plug in. Everything else --
the Groq call, graceful fallback, metric math -- is ready to run.
"""

from __future__ import annotations

import json
import re
import statistics

from groq import Groq

from config import GROQ_API_KEY, LLM_MODEL

# Lazy-safe client: if there's no key yet, the app still runs and the signal
# returns a neutral 0.5 instead of crashing on import.
_client = Groq(api_key=GROQ_API_KEY) if GROQ_API_KEY else None


# =============================================================================
# Signal 1 — LLM-as-judge (Groq)                                    [Milestone 3]
# =============================================================================

# The judge prompt. Asks for a calibrated probability + one-line reason as JSON,
# and explicitly guards against the false-positive failure mode (over-flagging
# formal or non-native-English human writing) — see planning.md.
_JUDGE_SYSTEM_PROMPT = """\
You are a forensic text analyst. Judge whether a passage was written by a human \
or generated by an AI language model.

Weigh signals such as: uniform vs. varied sentence rhythm, generic vs. \
idiosyncratic word choice, hedging and boilerplate phrasing ("it is important \
to note"), over-even structure, personal voice, specific lived detail, and \
natural imperfection.

Calibration rules:
- ai_probability is your estimated probability the text is AI-generated: \
0.0 = certainly human, 1.0 = certainly AI.
- Use values near 0.5 when you are genuinely unsure. Do not force a confident \
answer.
- IMPORTANT: formal, polished, or non-native-English writing is still HUMAN. \
Do not raise ai_probability just because prose is formal or grammatically clean. \
Calling a human's work AI is the costlier mistake.

Respond with ONLY a JSON object, no prose:
{"ai_probability": <number 0..1>, "reason": "<one short sentence>"}"""


def llm_signal(text: str) -> dict:
    """Ask the LLM how likely `text` is AI-generated.

    Returns {"score": float in [0,1] (P(AI)), "reason": str}.
    """
    if _client is None:
        return {"score": 0.5, "reason": "No GROQ_API_KEY set; neutral fallback."}

    try:
        resp = _client.chat.completions.create(
            model=LLM_MODEL,
            messages=[
                {"role": "system", "content": _JUDGE_SYSTEM_PROMPT},
                {"role": "user", "content": text},
            ],
            temperature=0,
            response_format={"type": "json_object"},  # Groq JSON mode
        )
        raw = resp.choices[0].message.content
        score, reason = _parse_llm_output(raw)
        return {"score": score, "reason": reason}
    except Exception as exc:  # network / parse / auth — fail to neutral, never crash
        return {"score": 0.5, "reason": f"LLM error, neutral fallback: {exc}"}


def _parse_llm_output(raw: str) -> tuple[float, str]:
    """Pull a 0..1 probability and a reason out of the model's JSON reply.

    Primary path is json.loads (JSON mode makes this reliable); if that ever
    fails, fall back to grabbing the first decimal so the signal degrades to a
    usable number rather than crashing.
    """
    try:
        data = json.loads(raw)
        score = float(data.get("ai_probability", 0.5))
        reason = str(data.get("reason", "")).strip()
    except (ValueError, TypeError, AttributeError):
        match = re.search(r"(\d*\.\d+|\d+)", raw or "")
        score = float(match.group(1)) if match else 0.5
        reason = (raw or "").strip()[:200]
    return max(0.0, min(1.0, score)), reason


# =============================================================================
# Signal 2 — Stylometric heuristics (pure Python)                   [Milestone 4]
# =============================================================================

def stylometric_signal(text: str) -> dict:
    """Structural statistics of the text mapped to P(AI). No API call.

    Returns {"score": float in [0,1] (P(AI)), "metrics": {...}}.

    Design (Milestone 4), calibrated on the sample texts:
      - Burstiness (sentence-length variance) is the PRIMARY driver: human prose
        mixes short and long sentences (high variance); AI prose is more uniform
        (low variance). Weighted 0.7.
      - Lexical diversity (type-token ratio) is SECONDARY: low TTR = repetitive =
        AI-leaning. Weighted 0.3. It is length-confounded and near-useless on
        short texts, hence the lower weight.
      - Average sentence length is deliberately NOT used to raise the AI score:
        long sentences signal formality, and formal humans are the group we most
        want to avoid false-positiving.
      - Short-text damping: on very short samples the statistics are unreliable
        (planning.md edge case #2), so the score is pulled toward 0.5.
    """
    metrics = compute_metrics(text)

    # Low variance (uniform) -> AI (0.85); high variance (bursty) -> human (0.15).
    ai_burstiness = _linmap(
        metrics["sentence_length_variance"], lo=10.0, hi=40.0, at_lo=0.85, at_hi=0.15
    )
    # Low TTR (repetitive) -> AI (0.80); high TTR (diverse) -> human (0.20).
    ai_diversity = _linmap(
        metrics["type_token_ratio"], lo=0.55, hi=0.85, at_lo=0.80, at_hi=0.20
    )

    score = 0.7 * ai_burstiness + 0.3 * ai_diversity

    # Reliability damping toward "no evidence" (0.5) for tiny samples.
    words = metrics["word_count"]
    if words < 25:
        score = 0.5 + (score - 0.5) * (words / 25.0)

    return {"score": round(max(0.0, min(1.0, score)), 3), "metrics": metrics}


def _linmap(x: float, lo: float, hi: float, at_lo: float, at_hi: float) -> float:
    """Linearly map x in [lo, hi] to [at_lo, at_hi], clamped at the ends."""
    if hi == lo:
        return (at_lo + at_hi) / 2.0
    t = max(0.0, min(1.0, (x - lo) / (hi - lo)))
    return at_lo + t * (at_hi - at_lo)


def compute_metrics(text: str) -> dict:
    """Compute a few interpretable stylometric features (starting set)."""
    words = re.findall(r"\b\w+\b", text.lower())
    sentences = [s for s in re.split(r"[.!?]+", text) if s.strip()]
    sentence_lengths = [len(re.findall(r"\b\w+\b", s)) for s in sentences]

    word_count = len(words)
    unique_words = len(set(words))

    return {
        "word_count": word_count,
        "sentence_count": len(sentences),
        # Vocabulary diversity: unique / total. Lower can indicate repetition.
        "type_token_ratio": round(unique_words / word_count, 3) if word_count else 0.0,
        # Burstiness: humans mix short and long sentences; AI is often uniform.
        "sentence_length_variance": (
            round(statistics.pvariance(sentence_lengths), 3)
            if len(sentence_lengths) > 1 else 0.0
        ),
        "avg_sentence_length": (
            round(statistics.mean(sentence_lengths), 2) if sentence_lengths else 0.0
        ),
        # Punctuation density: variety/rate of punctuation per word.
        "punctuation_density": (
            round(len(re.findall(r"[,;:\-—()\"']", text)) / word_count, 3)
            if word_count else 0.0
        ),
    }
